	////////////////////////////////////////////////////////////////
	//
	//	SplitMix64
	//
// @randx-include ../common/engines/splitmix64.inc

// @randx-include ../common/engines/splitmix64_shared_tail.inc

	////////////////////////////////////////////////////////////////
	//
	//	xoshiro256**
	//
// @randx-include ../common/engines/xoshiro256_star_star_next_definition.inc

// @randx-include ../common/engines/jump_method_definitions.inc

	////////////////////////////////////////////////////////////////
	//
	//	xoroshiro128**
	//
// @randx-include ../common/engines/xoroshiro128_star_star_next_definition.inc

// @randx-include ../common/engines/xoroshiro128_jump_definitions.inc

	////////////////////////////////////////////////////////////////
	//
	//	xoshiro128**
	//
// @randx-include ../common/engines/xoshiro128_star_star_next_definition.inc

// @randx-include ../common/engines/xoshiro128_jump_definitions.inc

	////////////////////////////////////////////////////////////////
	//
	//	xoroshiro64**
	//
// @randx-include ../common/engines/xoroshiro64_star_star_next_definition.inc

	////////////////////////////////////////////////////////////////
	//
	//	SFC64 (Small Fast Counter)
	//
// @randx-include ../common/engines/sfc64_sfc64_definition.inc

// @randx-include ../common/engines/sfc64_next_definition.inc

	////////////////////////////////////////////////////////////////
	//
	//	RomuDuoJr
	//
// @randx-include ../common/engines/romu_duo_jr_next_definition.inc
